car_inventory/blueprints/site/routes.py
from flask import Blueprint, render_template, request, flash, redirect

# internal imports
from car_inventory.models import Product, Customer, ProdOrder, Order, db, product_schema, products_schema
from car_inventory.forms import ProductForm


# instantiate Blueprint object
site = Blueprint('site', __name__, template_folder='site_templates')



# first route
@site.route('/')
def car_shop():


    shop = Product.query.all()
    customers = Customer.query.all()
    orders = Order.query.all()

    shop_stats = {
        'products': len(shop),
        'sales': sum([order.order_total for order in orders]),
        'customers': len(customers)
    }

    return render_template('car_shop.html', shop=shop, stats=shop_stats) # displays the car shop page


# create the CREATE route
@site.route('/shop/create', methods= ['GET', 'POST'])
def create():

    createform = ProductForm()

    if request.method == 'POST' and createform.validate_on_submit():

        
            name = createform.name.data
            desc = createform.description.data
            image = createform.image.data
            year = createform.year.data
            make = createform.make.data
            model = createform.model.data
            color = createform.color.data
            miles = createform.miles.data
            price = createform.price.data
            quantity = createform.quantity.data

            shop = Product(name, year, make, model, color, miles, price, quantity, image, desc)

            db.session.add(shop)
            db.session.commit()

            flash(f" {name} added successfully.", category='success')
            return redirect('/')
    
        
    return render_template('create.html', form=createform)


# create the UPDATE route
@site.route('/shop/update/<id>', methods= ['GET', 'POST'])
def update(id):

    updateform = ProductForm()
    product = Product.query.get(id)

    if request.method == 'POST' and updateform.validate_on_submit():

        
        try:
            product.name = updateform.name.data
            product.description = updateform.description.data
            product.set_image(updateform.image.data, updateform.name.data)
            product.year = updateform.year.data
            product.make = updateform.make.data
            product.model = updateform.model.data
            product.color = updateform.color.data
            product.miles = updateform.miles.data
            product.price = updateform.price.data
            product.quantity = updateform.quantity.data


            db.session.commit()

            flash(f" {product.name} updated successfully.", category='success')
            return redirect('/')

        except:
            flash("Process could not be completed. Please try again.")
            return redirect('/shop/update')
        
    return render_template('update.html', form=updateform, product=product)

@site.route('/shop/delete/<id>')
def delete(id):

    product = Product.query.get(id)

    db.session.delete(product)
    db.session.commit()

    return redirect('/')

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Car Inventory Shop"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Exclusive Luxury Motorsports - Car Inventory</title>
</head>
<body>

    {% include 'navbar.html' %}

    
   
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ category.title() }}</strong>{{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> 
     
        
        {% endfor %}
    {% endwith %}
        
    
    {% block content %}
    {% endblock content %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand link-light" href="/">EXCLUSIVE LUXURY MOTORSPORTS - CAR INVENTORY</a>
      <button class="navbar-toggler bg-dark-subtle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active link-light" aria-current="page" href="/">Home</a>
          </li>

          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active link-light" href="/logout">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active link-light" href="{{url_for('site.create' )}}">Add To Inventory</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link active link-light" href="/signin">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active link-light" href="/signup">Register</a>
          </li>

          {% endif %}
        </ul>

        
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-warning" disabled type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>